# Generated by Django 2.0.2 on 2018-02-12 21:56

from django.db import migrations, models
import django.db.models.deletion
import django_uuid_upload
import functools


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automaker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Automaker Name')),
                ('country', models.CharField(max_length=64, verbose_name='Country of Origin')),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=64, verbose_name='Vehicle Color')),
                ('mileage', models.IntegerField(verbose_name='Vehicle mileage (in KM)')),
                ('engine_volume', models.IntegerField(verbose_name='Engine Volume (in milliliters)')),
                ('vanity_photo', models.ImageField(null=True, upload_to=functools.partial(django_uuid_upload._upload_to_uuid_impl, *(), **{'make_dir': False, 'path': 'vanity_pictures', 'remove_qs': True}), verbose_name='Stock Photo of the Model')),
            ],
        ),
        migrations.CreateModel(
            name='VehicleModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.IntegerField(choices=[(1, 'CAR'), (2, 'MOTORCYCLE'), (3, 'SUV'), (4, 'TRUCK')], verbose_name='Vehicle Type')),
                ('name', models.CharField(max_length=64, verbose_name='Model Name')),
                ('stock_photo', models.ImageField(default='models_pictures/no_image.png', upload_to=functools.partial(django_uuid_upload._upload_to_uuid_impl, *(), **{'make_dir': False, 'path': 'models_pictures', 'remove_qs': True}), verbose_name='Stock Photo of the Model')),
                ('automaker', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_catalog.Automaker', verbose_name='Automaker')),
            ],
        ),
        migrations.AddField(
            model_name='vehicle',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auto_catalog.VehicleModel', verbose_name='Vehicle Model'),
        ),
    ]
